##############서버설정############
server:
  port: 80
  servlet.context-path: /user_spring_thymeleaf
##default-servlet활성화################# 
  servlet: 
    register-default-servlet: true  
##인코딩필터설정##################     
    encoding: 
      charset: UTF-8
      enabled: true
      force: true
      
spring:
##데이타베이스설정#################
  datasource: 
    url: jdbc:oracle:thin:@182.237.126.19:1521:XE
    username: jdeveloper30
    password: jdeveloper30
##메세지소스설정####################
  messages:
    basename: messages/message
##thymeleaf설정#####################    
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false
#로그설정##########################
logging:
  level:
    root: info
    org:
      springframework: 
        beans: debug
        context: debug 
        web: debug
        


