####################\ub370\uc774\ud0c0\ubca0\uc774\uc2a4\uc124\uc815####################
spring.datasource.url=jdbc:oracle:thin:@182.237.126.19:1521:XE
spring.datasource.username=jdeveloper44
spring.datasource.password=jdeveloper44
spring.output.ansi.enabled=ALWAYS
####################\ucd08\uae30\ud654\uc2dc\uc5d0 sql\ubb38\uc2e4\ud589####################




####################MyBatis\uc124\uc815####################
# mapper.xml \uc704\uce58 \uc9c0\uc815
mybatis.mapper-locations=com/itwill/guest/dao/mybatis/mapper/*.xml
# model \ud504\ub85c\ud37c\ud2f0 camel case \uc124\uc815
mybatis.configuration.map-underscore-to-camel-case=true

# \ud328\ud0a4\uc9c0 \uba85\uc744 \uc0dd\ub7b5\ud560 \uc218 \uc788\ub3c4\ub85d alias \uc124\uc815

# mapper \ub85c\uadf8\ub808\ubca8 \uc124\uc815
logging.level.com.mybatis3.dao=trace














