server:
  port: 9055
logging:
  level:
    org: 
      springframework: 
        security: DEBUG
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true

  datasource:
    url: jdbc:oracle:thin:@182.237.126.19:1521:XE
    username: jdeveloper44
    password: jdeveloper44
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate: 
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
    
    
    
    